package hs.jfx.eventstream.domain;

import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

import javafx.beans.value.ObservableValue;

/**
 * A sequence of values supporting aggregate operations. The values
 * emitted from this stream are always a direct result from a change
 * occuring in the source of this stream.<p>
 *
 * Subscribers will receive changes only when they occur. If no changes
 * occur it is therefore possible that a subscription will never receive
 * a change.<p>
 *
 * The operations offered by this stream are null safe. Operations
 * accepting a {@link Function} or {@link Consumer} will never be given
 * a <code>null</code> value as input unless otherwise specified.<p>
 *
 * This is a lazy stream, which means that it only observes its source
 * when it has observers of its own.  When there are no subscribers,
 * this stream stop observing its source immediately.
 *
 * @param <T> the type of values the stream emits
 */
public interface ChangeStream<T> extends ObservableStream<T> {

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which only emits values matching the given predicate.
   *
   * @param predicate a {@link Predicate} which values must match to be emitted, cannot be null
   * @return a {@link ChangeStream} which only emits values matching the given predicate, never null
   */
  ChangeStream<T> filter(Predicate<T> predicate);

  /**
   * Returns a {@link ValueStream}, using this stream as its source,
   * which emits the given value as its default value for new subscribers.
   *
   * @param value a value to emit as default value for new subscribers
   * @return a {@link ValueStream} which emits the given value as its default value, never null
   */
  default ValueStream<T> withDefault(T value) {
    return withDefaultGet(() -> value);
  }

  /**
   * Returns a {@link ValueStream}, using this stream as its source,
   * which emits the value generated by the given defaultValueSupplier
   * as its default value for new subscribers.
   *
   * @param defaultValueSupplier a {@link Supplier} which supplies the value to emit as default value for new subscribers
   * @return a {@link ValueStream} which uses the given defaultValueSupplier to provide its default value, never null
   */
  ValueStream<T> withDefaultGet(Supplier<T> defaultValueSupplier);

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which emits values converted by the given mapper function.
   *
   * @param <U> the type of values the new stream emits
   * @param mapper a {@link Function} which converts a source value to a new value to emit, cannot be null
   * @return a {@link ChangeStream} which emits values converted by the given mapper function, never null
   */
  <U> ChangeStream<U> map(Function<? super T, ? extends U> mapper);

  /**
   * Returns a {@link ChangeStream} which, each time this stream emits a value,
   * obtains a new stream supplied by mapper and emits its values instead.<p>
   *
   * Note: ChangeStreams donot emit values eagerly, so when this stream
   * emits a value, the stream being tracked changes but a value will
   * only be emitted when that stream emits a value after tracking started.
   * See also {@link ValueStream#flatMap(Function)}.<p>
   *
   * An example where the source stream flat maps to change stream A or B,
   * note especially that a change of stream does not necessarily result in
   * an emission:
   * <pre>
   *            Time ---&gt;
   *       Source :--A---A--B--B--A--A---A--B---------&gt;
   * Changes of A :-3-4-7---8--7----4-----34---5--56--&gt;
   * Changes of B :-1---6---6----5---8----9---2---5---&gt;
   *     Tracking :--AAAAAAABBBBBBAAAAAAAAAABBBBBBBBB-&gt;
   *        Emits :---4-7---6----5--4-----34--2---5---&gt;
   * </pre>
   *
   * @param mapper a {@link Function} which returns an alternative stream for each value this stream emits, cannot be null
   * @return a {@link ChangeStream} which obtains a new stream supplied by mapper and emits its values instead, never null
   */
  <U> ChangeStream<U> flatMap(Function<? super T, ? extends ChangeStream<? extends U>> mapper);

  ChangeStream<T> peek(Consumer<? super T> sideEffect);

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which emits values from this stream unless the value was
   * <code>null</code> in which case it emits values from the supplied stream
   * until a new value is emitted from this stream.
   *
   * @param supplier a {@link Supplier} supplying an alternative stream when this stream emitted <code>null</code>, cannot be null
   * @return a {@link ChangeStream} which emits values from this stream unless the value was <code>null</code>
   *         in which case it emits values from the supplied stream, never null
   */
  ChangeStream<T> or(Supplier<? extends ChangeStream<? extends T>> supplier);

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which emits values from this stream but with <code>null</code>s
   * replaced with the given value.
   *
   * @param value a value to emit instead of <code>null</code>
   * @return a {@link ChangeStream} with <code>null</code>s replaced with the given value, never null
   */
  default ChangeStream<T> orElse(T value) {
    return orElseGet(() -> value);
  }

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which emits the same values as its source but with <code>null</code>s
   * replaced with the value supplied by the given {@link Supplier}.
   *
   * @param valueSupplier a {@link Supplier} which supplies the value to emit instead of <code>null</code>
   * @return a {@link ChangeStream} with <code>null</code>s replaced with the value supplied by the given {@link Supplier}, never null
   */
  ChangeStream<T> orElseGet(Supplier<T> valueSupplier);

  /**
   * Returns a {@link ChangeStream}, using this stream as its source,
   * which only observes this stream when {@code condition} is {@code true}.<p>
   *
   * Although similar to {@link #filter(Predicate)}, the condition is not
   * based on the actual values emitted by the source stream, and as such
   * the subscription to the source stream can be temporarily suspended when the
   * condition evaluates to false.<p>
   *
   * @param condition a boolean {@link ObservableValue}, cannot be null
   * @return a {@link ChangeStream} which only observes its source stream when {@code condition} is {@code true}, never null
   */
  ChangeStream<T> conditionOn(ObservableValue<Boolean> condition);

  // Experimental
  ChangeStream<T> transactional();
}
